import { CropInfo } from '../types/agricultural';

/**
 * KrishiSahay Structured Crop Agronomic Database
 * Note: Values are calibrated reference figures based on ICAR, TNAU, and State Agronomic Extension guides.
 * Clearly identified for hackathon simulation and decision-support modeling.
 */
export const CROPS_DATABASE: CropInfo[] = [
  {
    id: 'rice',
    name: 'Rice (Paddy)',
    scientificName: 'Oryza sativa',
    category: 'Cereal',
    suitableSeasons: ['Kharif (Monsoon)', 'Zaid (Summer)'],
    durationDays: 130,
    waterRequirementMm: 1200,
    waterRequirementM3PerHa: 12000,
    expectedYieldTonPerHa: 4.8,
    costPerHa: 42000,
    marketPricePerTon: 23500, // ~MSP ₹2300-2400/qtl
    nitrogenDemandKgPerHa: 110,
    phosphorusDemandKgPerHa: 45,
    potassiumDemandKgPerHa: 50,
    organicMatterImpact: -1.2,
    diseaseRiskBase: 42,
    diseaseFamily: 'Poaceae',
    droughtTolerance: 'Low',
    compatiblePreceding: ['chickpea', 'soybean', 'groundnut', 'wheat'],
    compatibleFollowing: ['wheat', 'chickpea', 'potato', 'onion'],
    soilTypeCompatibility: ['Clay', 'Alluvial', 'Loamy', 'Black Cotton'],
    carbonSequestrationKgPerHa: 180,
    description: 'High-calorie staple grain requiring standing water or high soil moisture saturation.',
    keyBenefits: ['Stable MSP government procurement', 'High total caloric volume', 'Ideal for low-drainage clay soils']
  },
  {
    id: 'wheat',
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    category: 'Cereal',
    suitableSeasons: ['Rabi (Winter)'],
    durationDays: 120,
    waterRequirementMm: 450,
    waterRequirementM3PerHa: 4500,
    expectedYieldTonPerHa: 4.2,
    costPerHa: 34000,
    marketPricePerTon: 22750, // ~MSP ₹2275/qtl
    nitrogenDemandKgPerHa: 95,
    phosphorusDemandKgPerHa: 40,
    potassiumDemandKgPerHa: 40,
    organicMatterImpact: -0.8,
    diseaseRiskBase: 30,
    diseaseFamily: 'Poaceae',
    droughtTolerance: 'Moderate',
    compatiblePreceding: ['rice', 'soybean', 'cotton', 'maize', 'groundnut'],
    compatibleFollowing: ['maize', 'millets', 'soybean', 'groundnut'],
    soilTypeCompatibility: ['Loamy', 'Alluvial', 'Black Cotton', 'Clay'],
    carbonSequestrationKgPerHa: 220,
    description: 'Premier Rabi staple with established cold tolerance and predictable market returns.',
    keyBenefits: ['Low irrigation needs compared to paddy', 'Residue mulch enriches topsoil', 'High local market demand']
  },
  {
    id: 'maize',
    name: 'Maize (Corn)',
    scientificName: 'Zea mays',
    category: 'Cereal',
    suitableSeasons: ['Kharif (Monsoon)', 'Rabi (Winter)', 'Zaid (Summer)'],
    durationDays: 105,
    waterRequirementMm: 500,
    waterRequirementM3PerHa: 5000,
    expectedYieldTonPerHa: 5.5,
    costPerHa: 36000,
    marketPricePerTon: 21500,
    nitrogenDemandKgPerHa: 100,
    phosphorusDemandKgPerHa: 50,
    potassiumDemandKgPerHa: 60,
    organicMatterImpact: -0.5,
    diseaseRiskBase: 28,
    diseaseFamily: 'Poaceae',
    droughtTolerance: 'Moderate',
    compatiblePreceding: ['chickpea', 'soybean', 'groundnut', 'potato'],
    compatibleFollowing: ['wheat', 'chickpea', 'soybean', 'tomato'],
    soilTypeCompatibility: ['Loamy', 'Alluvial', 'Red Soil', 'Sandy'],
    carbonSequestrationKgPerHa: 260,
    description: 'Fast-growing high-yield cereal ideal for grain, poultry feed, and industrial starch.',
    keyBenefits: ['Versatile multi-season suitability', 'Rapid biomass accumulation', 'Excellent livestock fodder value']
  },
  {
    id: 'cotton',
    name: 'Cotton',
    scientificName: 'Gossypium hirsutum',
    category: 'Cash / Commercial',
    suitableSeasons: ['Kharif (Monsoon)'],
    durationDays: 165,
    waterRequirementMm: 700,
    waterRequirementM3PerHa: 7000,
    expectedYieldTonPerHa: 2.3,
    costPerHa: 52000,
    marketPricePerTon: 71000, // ~₹7100/qtl
    nitrogenDemandKgPerHa: 120,
    phosphorusDemandKgPerHa: 60,
    potassiumDemandKgPerHa: 70,
    organicMatterImpact: -1.5,
    diseaseRiskBase: 50,
    diseaseFamily: 'Malvaceae',
    droughtTolerance: 'Moderate',
    compatiblePreceding: ['wheat', 'chickpea', 'millets', 'soybean'],
    compatibleFollowing: ['wheat', 'chickpea', 'millets'],
    soilTypeCompatibility: ['Black Cotton', 'Alluvial', 'Loamy'],
    carbonSequestrationKgPerHa: 190,
    description: 'High-value commercial fiber crop with deep taproots, sensitive to bollworm and whitefly.',
    keyBenefits: ['High gross revenue potential', 'Taproots aerate subsoil layers', 'Direct access to ginning mills']
  },
  {
    id: 'soybean',
    name: 'Soybean',
    scientificName: 'Glycine max',
    category: 'Pulse / Legume',
    suitableSeasons: ['Kharif (Monsoon)'],
    durationDays: 95,
    waterRequirementMm: 450,
    waterRequirementM3PerHa: 4500,
    expectedYieldTonPerHa: 2.4,
    costPerHa: 28000,
    marketPricePerTon: 46000, // ~₹4600/qtl
    nitrogenDemandKgPerHa: -35, // Fixes 35 kg N/ha net benefit!
    phosphorusDemandKgPerHa: 35,
    potassiumDemandKgPerHa: 40,
    organicMatterImpact: +2.4,
    diseaseRiskBase: 25,
    diseaseFamily: 'Fabaceae',
    droughtTolerance: 'Moderate',
    compatiblePreceding: ['wheat', 'rice', 'maize', 'millets'],
    compatibleFollowing: ['wheat', 'chickpea', 'onion', 'potato'],
    soilTypeCompatibility: ['Black Cotton', 'Loamy', 'Alluvial'],
    carbonSequestrationKgPerHa: 310,
    description: 'Premier nitrogen-fixing legume with high protein and edible oil content.',
    keyBenefits: ['Fixes ~35kg/ha atmospheric nitrogen', 'Breaks soil-borne cereal pathogen cycles', 'Short 95-day cycle']
  },
  {
    id: 'groundnut',
    name: 'Groundnut (Peanut)',
    scientificName: 'Arachis hypogaea',
    category: 'Pulse / Legume',
    suitableSeasons: ['Kharif (Monsoon)', 'Zaid (Summer)'],
    durationDays: 110,
    waterRequirementMm: 480,
    waterRequirementM3PerHa: 4800,
    expectedYieldTonPerHa: 2.5,
    costPerHa: 35000,
    marketPricePerTon: 62000, // ~₹6200/qtl
    nitrogenDemandKgPerHa: -30, // Fixes 30 kg N/ha
    phosphorusDemandKgPerHa: 30,
    potassiumDemandKgPerHa: 45,
    organicMatterImpact: +2.1,
    diseaseRiskBase: 30,
    diseaseFamily: 'Fabaceae',
    droughtTolerance: 'High',
    compatiblePreceding: ['wheat', 'maize', 'millets'],
    compatibleFollowing: ['wheat', 'onion', 'chickpea', 'rice'],
    soilTypeCompatibility: ['Sandy', 'Loamy', 'Red Soil'],
    carbonSequestrationKgPerHa: 280,
    description: 'Valuable oilseed legume fixing nitrogen while thriving in loose, well-drained sandy loams.',
    keyBenefits: ['Leaves soil rich in residual nitrogen', 'High oil and oilcake profitability', 'Tolerates intermittent dry spells']
  },
  {
    id: 'chickpea',
    name: 'Chickpea (Gram)',
    scientificName: 'Cicer arietinum',
    category: 'Pulse / Legume',
    suitableSeasons: ['Rabi (Winter)'],
    durationDays: 100,
    waterRequirementMm: 300,
    waterRequirementM3PerHa: 3000,
    expectedYieldTonPerHa: 1.9,
    costPerHa: 22000,
    marketPricePerTon: 54000, // ~₹5400/qtl
    nitrogenDemandKgPerHa: -40, // Fixes 40 kg N/ha!
    phosphorusDemandKgPerHa: 25,
    potassiumDemandKgPerHa: 30,
    organicMatterImpact: +2.8,
    diseaseRiskBase: 22,
    diseaseFamily: 'Fabaceae',
    droughtTolerance: 'High',
    compatiblePreceding: ['rice', 'maize', 'cotton', 'millets', 'soybean'],
    compatibleFollowing: ['maize', 'millets', 'rice', 'cotton'],
    soilTypeCompatibility: ['Black Cotton', 'Loamy', 'Alluvial', 'Red Soil'],
    carbonSequestrationKgPerHa: 340,
    description: 'Premier low-water winter pulse that fixes substantial nitrogen and restores soil health.',
    keyBenefits: ['Lowest water requirement among Rabi crops', 'Maximum nitrogen restoration (+40 kg/ha)', 'High domestic pulse demand']
  },
  {
    id: 'tomato',
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'Vegetable',
    suitableSeasons: ['Rabi (Winter)', 'Zaid (Summer)', 'Kharif (Monsoon)'],
    durationDays: 110,
    waterRequirementMm: 600,
    waterRequirementM3PerHa: 6000,
    expectedYieldTonPerHa: 28.0,
    costPerHa: 85000,
    marketPricePerTon: 14000, // ₹14/kg wholesale (volatile)
    nitrogenDemandKgPerHa: 140,
    phosphorusDemandKgPerHa: 70,
    potassiumDemandKgPerHa: 120,
    organicMatterImpact: -0.9,
    diseaseRiskBase: 58,
    diseaseFamily: 'Solanaceae',
    droughtTolerance: 'Low',
    compatiblePreceding: ['wheat', 'chickpea', 'soybean', 'millets'],
    compatibleFollowing: ['maize', 'chickpea', 'millets'],
    soilTypeCompatibility: ['Loamy', 'Red Soil', 'Alluvial', 'Sandy'],
    carbonSequestrationKgPerHa: 120,
    description: 'Intensive horticultural cash crop with massive profit ceiling but acute price and pest volatility.',
    keyBenefits: ['Extraordinary gross margin during favorable markets', 'Frequent harvest cashflow', 'Responsive to fertigation']
  },
  {
    id: 'potato',
    name: 'Potato',
    scientificName: 'Solanum tuberosum',
    category: 'Vegetable',
    suitableSeasons: ['Rabi (Winter)'],
    durationDays: 95,
    waterRequirementMm: 500,
    waterRequirementM3PerHa: 5000,
    expectedYieldTonPerHa: 24.0,
    costPerHa: 78000,
    marketPricePerTon: 12500,
    nitrogenDemandKgPerHa: 130,
    phosphorusDemandKgPerHa: 65,
    potassiumDemandKgPerHa: 140,
    organicMatterImpact: -0.7,
    diseaseRiskBase: 52,
    diseaseFamily: 'Solanaceae',
    droughtTolerance: 'Low',
    compatiblePreceding: ['rice', 'soybean', 'maize', 'millets'],
    compatibleFollowing: ['maize', 'groundnut', 'millets', 'soybean'],
    soilTypeCompatibility: ['Loamy', 'Sandy', 'Alluvial'],
    carbonSequestrationKgPerHa: 140,
    description: 'High-density tuber crop requiring cool nights, fertile loose soil, and intensive potash.',
    keyBenefits: ['Very high yield per hectare', 'Short 95-day winter turnaround', 'High industrial processing demand']
  },
  {
    id: 'onion',
    name: 'Onion',
    scientificName: 'Allium cepa',
    category: 'Vegetable',
    suitableSeasons: ['Rabi (Winter)', 'Kharif (Monsoon)'],
    durationDays: 125,
    waterRequirementMm: 550,
    waterRequirementM3PerHa: 5500,
    expectedYieldTonPerHa: 18.0,
    costPerHa: 65000,
    marketPricePerTon: 19000, // ₹19/kg
    nitrogenDemandKgPerHa: 90,
    phosphorusDemandKgPerHa: 45,
    potassiumDemandKgPerHa: 80,
    organicMatterImpact: -0.4,
    diseaseRiskBase: 38,
    diseaseFamily: 'Amaryllidaceae',
    droughtTolerance: 'Moderate',
    compatiblePreceding: ['soybean', 'groundnut', 'rice', 'wheat'],
    compatibleFollowing: ['maize', 'millets', 'wheat', 'chickpea'],
    soilTypeCompatibility: ['Loamy', 'Alluvial', 'Red Soil'],
    carbonSequestrationKgPerHa: 160,
    description: 'Bulb spice crop with strong consumer demand, sensitive to waterlogging and thrips.',
    keyBenefits: ['High market liquidity and storage potential', 'Good preceding crop break for non-allium pests', 'High commercial value']
  },
  {
    id: 'millets',
    name: 'Millets (Finger / Pearl Millet)',
    scientificName: 'Eleusine coracana / Pennisetum glaucum',
    category: 'Millet',
    suitableSeasons: ['Kharif (Monsoon)', 'Zaid (Summer)'],
    durationDays: 85,
    waterRequirementMm: 250,
    waterRequirementM3PerHa: 2500,
    expectedYieldTonPerHa: 2.8,
    costPerHa: 18000,
    marketPricePerTon: 33000, // ~₹3300/qtl
    nitrogenDemandKgPerHa: 45,
    phosphorusDemandKgPerHa: 20,
    potassiumDemandKgPerHa: 25,
    organicMatterImpact: +1.5,
    diseaseRiskBase: 14,
    diseaseFamily: 'Poaceae',
    droughtTolerance: 'Very High',
    compatiblePreceding: ['cotton', 'rice', 'tomato', 'potato', 'chickpea'],
    compatibleFollowing: ['wheat', 'chickpea', 'onion', 'mustard'],
    soilTypeCompatibility: ['Sandy', 'Red Soil', 'Loamy', 'Black Cotton', 'Clay'],
    carbonSequestrationKgPerHa: 380,
    description: 'Nutri-cereal supercrop with extreme drought resilience, minimal fertilizer requirements, and climate immunity.',
    keyBenefits: ['Cuts irrigation water by over 60%', 'Lowest disease incidence (<15%)', 'Thrives in nutrient-poor and dry soils']
  }
];

export function getCropById(id: string): CropInfo {
  const crop = CROPS_DATABASE.find(c => c.id === id);
  if (!crop) {
    return CROPS_DATABASE[0]; // fallback
  }
  return crop;
}

export function getCropsForSeason(seasonName: string): CropInfo[] {
  return CROPS_DATABASE.filter(c => c.suitableSeasons.includes(seasonName as any));
}
